# Generated by Django 4.0.4 on 2022-05-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Product Name")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Product price"
                    ),
                ),
                (
                    "quantity_in_stock",
                    models.PositiveIntegerField(verbose_name="Product quantity"),
                ),
            ],
        ),
    ]
